src/commands/generate.ts
src/commands/list.ts
src/template/reader.ts

This PR fixes `list` and `generate` commands' behavior abount their file resolution on Windows.
Before this change, the `list` command cannot find any `.md` files and the `generate` command cannot find any templates.
The above problem is caused by `globby`'s complicated behavior.
According to its [API documentation](https://github.com/sindresorhus/globby#api), glob patterns must be constructed using not backward-slashes but forward-slashes.
On Windows, `process.cwd()` and `path.join()` return path strings containing backward-slashes.
Thus, `globby.sync(...)` (at `src/template/reader.ts`) always returns empty array.
Consequently, the above problem occurs.
This PR fixes it in the following steps.
1. Add logic that the backward-slashes which appear in the path string are replaced with …

Add windows support

---

README.md

Since the descriptions about development environment in README remains unchanged though this project uses ESLint (+ typescript-eslint) instead of TSLint from #86, I updated them.

Update descriptions about development environment

---

src/template/reader.ts

Previously, when the `fm` function (exported from `front-matter` module) takes no type arguments, its return type has been inferred to `FrontMatterResult<any>`.
Thus, the following code (including spread operator with `any` value) has been compiled successfully.
https://github.com/cats-oss/scaffdog/blob/44be9293d6354a2ee1c5ee80ad3f1ba03f231840/src/template/reader.ts#L36-L57
If we migrate from TS 3.7 to 3.8, however, the inferred type of `fm(markdown)` is changed to `FrontMatterResult<unknown>`.
Under the influence of the breaking change, the compilation in [this workflow](https://github.com/cats-oss/scaffdog/runs/475927829?check_suite_focus=true) failed.
Therefore, I updated type declarations so that this project is compiled successfully also in TS 3.8 or later.
1. Define …

Fix type declarations which prevent migration to typescript 3.8

---

src/template/tokenize.ts

This PR refactors tokenizer according to the following policies.
- Try to use `const` instead of `let` as much as possible
- Try to reduce human errors TypeScript compiler cannot detect
- Try to simplify state transitions
1. Split up `tokenizeInTag` function into smaller functions
- `tokenizeUsingEsprima` : newly defined function, which deals with Esprima API call and its errors
2. Replace `<array variable> = [];` with `<array variable>.length = 0;` and change related `let` statements into `const` statements
- Modifying `length` property of array to `0` means to empty the array (About this behavior, please refer to [ECMAScript Specification (9.4.2 Array Exotic Objects)](https://www.ecma-international.org/ecma-262/9.0/#sec-array-exotic-objects))
3. Refactor functions so as not to mutate …

Refactor tokenizer

---

package.json

moves `@types/node` to devDependencies
Reason: to reduce size of node_modules for the user.
I was looking through my node_modules, trying to reduce size, and I noticed that `@types/node` was included in the dependencies instead of devDependencies, which results in `@types/node` being included in the node_modules inside the installed package.
moved `@types/node` to devDependencies so that it will not be included when user installs the package.
check that there are no type error for the users
n/a
n/a

chore: move @types/node to devDep

---

packages/@scaffdog/config/src/validator.test.ts
packages/@scaffdog/config/src/validator.ts
packages/@scaffdog/core/src/generate.test.ts
packages/@scaffdog/core/src/generate.ts
packages/@scaffdog/engine/README.md
packages/@scaffdog/engine/src/compile.test.ts
packages/@scaffdog/engine/src/compile.ts
packages/@scaffdog/engine/src/context.test.ts
packages/@scaffdog/engine/src/context.ts
packages/@scaffdog/engine/src/syntax.ts
packages/@scaffdog/engine/src/tokenize.test.ts
packages/@scaffdog/engine/src/tokenize.ts
packages/@scaffdog/engine/src/tokens.ts
packages/@scaffdog/types/src/config.ts
packages/@scaffdog/types/src/context.ts
packages/@scaffdog/types/src/index.ts
packages/@scaffdog/types/src/tag.ts
packages/scaffdog/README.md
packages/scaffdog/src/cmds/generate.ts

There are cases where we want to change the tag delimiter. For example, when outputting a file for the template engine.  
Allows you to change the tag delimiter from the configuration file to accommodate those cases.
```javascript
module.exports = {
files: ['./*'],
tags: ['<%', '%>'],
};
```
By setting the above config, `<%` and `%>` will be the tag delimiters in the template.
```
<% inputs.name %>
```
- n/a
- n/a
- n/a

Add custom tags

---

packages/@scaffdog/engine/src/helpers.test.ts
packages/@scaffdog/engine/src/helpers.ts
packages/scaffdog/README.md

When we generate code, we sometimes want to inject it into existing code.
- prepend
- append
- at (line / position)
- before
- after
So, We added the helper function required to realize the injection of the code.
n/a
n/a
- n/a

Add `before` / `after` helper functions

---

packages/@scaffdog/config/src/validator.ts

Fixed a bug where the `helpers` field in the configuration file differed from the defined type.
```javascript
module.exports = {
files: ['./*'],
helpers: [
{
key: () => '',
},
],
};
```
n/a
n/a

fix(config): fix config schema on loader

---

packages/scaffdog/.scaffdog/sandbox.md
packages/scaffdog/README.md
packages/scaffdog/fixtures/question.md
packages/scaffdog/src/cmds/__snapshots__/generate.test.ts.snap
packages/scaffdog/src/cmds/generate.test.ts
packages/scaffdog/src/cmds/generate.ts
packages/scaffdog/src/document.ts
packages/scaffdog/src/prompt.ts

Prompt has been added to meet the specifications of the new template engine.
```yaml
questions:
bool:
confirm: 'Do you need something?'
arr:
message: 'Please select elements.'
multiple: true
choices: ['A', 'B', 'C']
```
It should be useful for conditional branching and iteration :dog2:

Add confirm and checkbox question type

---

packages/scaffdog/src/cmds/generate.ts
packages/scaffdog/src/document.ts

Improved error message displayed when incorrect settings exist for front-matter in a document.
Until now, users have been unable to tell where they have gone wrong within yaml.
So, we have improved the display to show the paths and messages where validation failed.

Improve document parsing error message

---

packages/scaffdog/src/document.test.ts
packages/scaffdog/src/document.ts
website/content/docs/templates/attributes.mdx

Fixed a bug that caused parsing errors when `initial` in list prompt was specified.
```markdown
---
questions:
key:
- message: 'msg'
- choices: ['A', 'B]
- initial: 'A' <-- Parse error
---
```

fix(scaffdog): fix document parse bug

---

packages/@scaffdog/engine/src/helpers.test.ts
packages/@scaffdog/engine/src/helpers.ts
packages/scaffdog/.scaffdog/sandbox.md
packages/scaffdog/fixtures/question.md
packages/scaffdog/src/cmds/__snapshots__/generate.test.ts.snap
packages/scaffdog/src/cmds/generate.test.ts
packages/scaffdog/src/cmds/generate.ts
packages/scaffdog/src/document.test.ts
packages/scaffdog/src/document.ts
website/content/docs/templates/attributes.mdx
website/content/docs/templates/helpers.mdx
website/public/sitemap-0.xml

Added functionality for conditional branching on whether or not to invoke a prompt :dog:
````markdown
---
name: 'component'
root: '.'
output: '.'
questions:
name: 'Please a component name.'
test:
if: contains(inputs.name, 'Form')
confirm: 'Do you need a test?'
initial: false
---
```typescript
// ...
```
```typescript
// ...
```
````
This is a mechanism much like `if` in [GitHub Actions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif).

Add conditional prompt

---

packages/scaffdog/.scaffdog/sandbox.md
packages/scaffdog/fixtures/vars.md
packages/scaffdog/src/cmds/__snapshots__/generate.test.ts.snap
packages/scaffdog/src/cmds/generate.test.ts
packages/scaffdog/src/cmds/generate.ts

Bug fixes in the Variables Section.
````markdown
---
...
questions:
name: 'msg'
---
- name: `{{ inputs.name | pascal }}`
^^^^^^ <- Cannot reference
```
{{ name }}
```
````

fix(scaffdog): fix a bug that `inputs` could not be referenced in the variables section

---

packages/@scaffdog/core/src/extract.ts
packages/@scaffdog/engine/src/formatter.ts

The definition of the code block that will serve as the template is given the highest priority.
Previously, if a code block contained blank lines, it would be trimmed. This change modifies the output to take advantage of the given input as is.
Removed trim when core extracts code blocks from Markdown files.
- #437

Remove unnecessary trimming

---

website/content/docs/templates/helpers.mdx

in `n2s` helper section, signature written as `s2n`
fix that (s2n -> n2s)

docs: fix typo in `n2s` signature

---

packages/scaffdog/src/commands/__snapshots__/generate.test.ts.snap
packages/scaffdog/src/commands/generate.test.ts
packages/scaffdog/src/commands/generate.ts
website/content/docs/cli.mdx

Added flag to avoid `question` interaction prompts.
```bash
$ scaffdog generate component --answer "name:ScaffdogEditor"
```

feat(scaffdog): add `answer` flag

---

.changeset/pre.json
.changeset/three-pens-rhyme.md
packages/@scaffdog/config/src/loader.ts
packages/prettier-plugin-scaffdog/src/index.ts
packages/scaffdog/build.config.js
packages/scaffdog/package.json
packages/scaffdog/src/api.test.ts
packages/scaffdog/src/api.ts
packages/scaffdog/src/bin.ts
packages/scaffdog/src/cli.test.ts
packages/scaffdog/src/cli.ts
packages/scaffdog/src/command.ts
packages/scaffdog/src/commands/generate.test.ts
packages/scaffdog/src/commands/generate.ts
packages/scaffdog/src/commands/list.test.ts
packages/scaffdog/src/commands/list.ts
packages/scaffdog/src/file.factory.ts
packages/scaffdog/src/index.ts
packages/scaffdog/src/lib/config.ts
packages/scaffdog/src/mocks/api.ts
packages/scaffdog/src/mocks/command-test-utils.ts
packages/scaffdog/src/variables.ts
packages/scaffdog/test/__snapshots__/e2e.test.ts.snap
tsconfig.base.json
website/content/docs/api.mdx
website/routing/sidebar.ts

Added two Node APIs.
- `createScaffdog(options)`
- `loadScaffdog(path, options)`
It is a useful API for the programmatic use of scaffdog.
n/a
n/a
- n/a

Add Node API

---

.changeset/stupid-socks-jog.md
packages/scaffdog/src/index.ts

Add missing exports.
- `Variable`
- `Question*`
- `DocumentAttributes`
n/a
n/a
- n/a

fix(scaffdog): add missing exports

---

.changeset/spotty-windows-sip.md
packages/@scaffdog/error/src/index.test.ts
packages/@scaffdog/error/src/scaffdog-error.ts

Fixed an error report when a template with a blank line contains invalid syntax.
n/a
n/a
- n/a

fix(error): fix error report when a blank line is included

---

.changeset/eighty-cameras-walk.md
packages/@scaffdog/engine/package.json
packages/@scaffdog/engine/src/helpers.test.ts
packages/@scaffdog/engine/src/helpers.ts
packages/scaffdog/src/helpers.test.ts
packages/scaffdog/src/helpers.ts
pnpm-lock.yaml
website/app/playground/Playground.tsx
website/app/playground/PlaygroundPreview.tsx
website/package.json
website/states/playground.ts
website/utils/scaffdog.ts

Fixes for `safe-eval` vulnerability issues.
Fixes to remove `safe-eval` as a dependency and use `vm.runInNewContext` instead.
Since scaffdog is intended to be used in a development environment, it is assumed that the input code is safe. Do not use the `eval` helper function in situations where it receives input from third parties.
- See References section.
n/a
- #766

Remove `safe-eval` and use the `vm` module instead

---

website/content/docs/templates/attributes.mdx

The `output` attribute actually can handle `string[]` but it is not documented.
Fixed document.
The result of current PR is like
I also tested union type but the width was not automatically adjusted.
I'm not sure which is better. It might be better to adjust some CSS.
I read [this line](https://github.com/scaffdog/scaffdog/blob/68cdb4b5eeabe413f1256dbb935ec9f6917b0404/packages/scaffdog/src/commands/generate.ts#L124) and I thought it can handle array string.

docs: fix output attribute to be able to accept array string

---

packages/@scaffdog/engine/src/parser/statements.test.ts
packages/@scaffdog/engine/src/parser/statements.ts

When we use variables starting with `for`, such as `formula` and `forest`,  in tag template, we get an error below.
```
SyntaxError: "in" expected after expression:
```
In `for` statement, single whitespace will be required after `for` string.
I confirmed that `if` statement doesn't have the same problem, so I'm not confident that this approach is appropriate.
- Playground: https://scaff.dog/playground?code=H4sIAAAAAAAAA1NWCEssykxMykkt5uLSVUjLL8otzUm0UkgoSS0uSeDiUlZIqK5WyMwrKC0p1stLzE1VqK3VK6kASSUkJJRUFqQWJxdlFpRwAVVBNQNVgOS4AAy9ei1bAAAA&input=H4sIAAAAAAAAA4uuVspOrVSyUspLzE1V0lEqS8wpTQVyi5MT09JS8tOVamMBz%2B0iZCMAAAA%3D

fix: correct parsing variable starting with `for`

---

MIGRATION.md

Fixed an incorrect section title in the migration guide. The title was "to v3" but it should have been "to v4".
Updates the section title from "to v3" to "to v4".
Please confirm that the section title has been correctly updated to "to v4" and that no other changes are necessary.
- N/A

doc: fix section title to v4 from v3

---

website/content/docs/index.mdx

The URL to the React documentation in the documentation is out of date.
The documentation at this link is currently inaccessible and redirects.
The URLs listed in MDX have been changed to the new ones.
Whether the URLs are appropriate. Whether the relevant URLs in the documentation have been changed to the desired ones after deployment.
- Old React document link: [https://reactjs.org](https://reactjs.org)
- New React document link: [https://react.dev](https://react.dev)

chore: update React link in documentation example
