scaffdog/scaffdog

- .scaffdog/broken.md
- src/commands/generate.ts
- src/template/compiler.ts
- src/template/error.ts
- src/template/parser.ts
- src/template/reader.ts
- src/template/reporter.test.ts
- src/template/reporter.ts
- src/template/tokenize.test.ts
- src/template/tokenize.ts
- src/template/tokens.ts
Improved error message when parsing template failed.
**Example output:**
```
? Please select the output destination directory. tmp
? Please enter any text. oge
Template parsing error:
{{ hoge
^^ unclosing tag
SyntaxError: unopened tag
at unclosed (~/develop/github.com/cats-oss/scaffdog/src/template/tokenize.ts:22:9)
at Object.exports.tokenize (~/develop/github.com/cats-oss/scaffdog/src/template/tokenize.ts:292:5)
at Function.compile (~/develop/github.com/cats-oss/scaffdog/src/template/compiler.ts:8:31)
at ~/develop/github.com/cats-oss/scaffdog/src/commands/generate.ts:144:37
at Array.map (<anonymous>)
at GenerateCommand.run (~/develop/github.com/cats-oss/scaffdog/src/commands/generate.ts:122:40)
at GenerateCommand._run (~/develop/github.com/cats-oss/scaffdog/node_modules/@oclif/command/ …
```
> feat: Improve error message

- src/commands/generate.ts
> fix typo from combpiled to compiled

- .github/PULL_REQUEST_TEMPLATE.md
Fixes the grammar in the pull request template
Fixes the grammar in the pull request template
Wording
n/a
n/a
> docs: fixes grammar

- package.json
- yarn.lock
{Please write here}
{Please write here}
{Please write here}
{Please write here}
> chore: Update deps

- README.md
- package.json
- src/template/funcs.ts
- yarn.lock
I added the function `date` as a function that can be used in templates, which can be used with the following syntax
It can be used with the following syntax:
```markdown
{{ date }} // --> 2020-08-09T16:42:40.648Z
{{ date "YYYY-MM-DD" }} // --> 2020-08-09
```
:dog:
:dog:
:dog:
> feat: Add `date` function

- packages/@scaffdog/error/README.md
- packages/@scaffdog/error/src/index.test.ts
- packages/@scaffdog/error/src/index.ts
- packages/scaffdog/src/cmds/generate.ts
> feat(error): add `format` method

- packages/@scaffdog/config/package.json
- packages/@scaffdog/core/package.json
- packages/@scaffdog/engine/package.json
- packages/@scaffdog/error/package.json
- packages/scaffdog/package.json
Getting an error when it installed the packages individually.
n/a
n/a
n/a
> fix: move @scaffdog/types to dependencies from devDependencies

- package.json
- packages/@scaffdog/engine/src/tokenize.ts
- packages/@scaffdog/types/package.json
- packages/scaffdog/package.json
- packages/scaffdog/src/cli.ts
- yarn.lock
{Please write here}
{Please write here}
{Please write here}
- {Please write here}
> chore: typescript

- .github/workflows/ci.yml
- change cache strategy
- add matrix testing
n/a
n/a
n/a
> CI Improvement

- packages/scaffdog/package.json
- yarn.lock
> Revert "chore: update dependency valid-filename to v4"

- packages/@scaffdog/engine/src/tokenize.test.ts
- packages/@scaffdog/engine/src/tokenize.ts
> Fix parser error when using tag keyword in string

- packages/@scaffdog/engine/src/helpers.test.ts
- packages/@scaffdog/engine/src/helpers.ts
- packages/scaffdog/README.md
> Add `head` / `tail` helper functions

- packages/@scaffdog/engine/src/helpers.test.ts
- packages/@scaffdog/engine/src/helpers.ts
- packages/scaffdog/README.md
> Revert "Add `head` / `tail` helper functions"

- packages/@scaffdog/core/src/generate.test.ts
- packages/@scaffdog/core/src/generate.ts
- packages/scaffdog/README.md
> feat(core): add `output.root` variable

- packages/scaffdog/README.md
- packages/scaffdog/src/cmds/create.ts
- packages/scaffdog/src/cmds/init.ts
- website/content/docs/index.mdx
> fix: update initial template url

- website/content/docs/templates/helpers.mdx
Fix docs
Fix helper `resolve` signature typo
> docs: fix resolve signature

- website/content/docs/templates/index.mdx
Fix docs
Fix conditional generates example.
It's more reasonable to generate the test file when `inputs.test` is `true`.
> docs: fix conditional generates example

- .changeset/friendly-flowers-carry.md
- packages/scaffdog/src/api.test.ts
- packages/scaffdog/src/api.ts
- packages/scaffdog/src/bin.ts
- packages/scaffdog/src/commands/list.test.ts
- packages/scaffdog/src/commands/list.ts
- packages/scaffdog/src/index.ts
- packages/scaffdog/src/lib/__snapshots__/error.test.ts.snap
- packages/scaffdog/src/lib/document.factory.ts
- packages/scaffdog/src/lib/document.test.ts
- packages/scaffdog/src/lib/document.ts
- packages/scaffdog/src/lib/error.test.ts
- packages/scaffdog/src/lib/error.ts
- packages/scaffdog/src/lib/index.ts
- packages/scaffdog/src/lib/question.mock.ts
- packages/scaffdog/src/lib/question.test.ts
- packages/scaffdog/src/lib/question.ts
- packages/scaffdog/src/mocks/api.ts
- Add `version` export.
- Report document parsing errors at an early stage.
n/a
n/a
- n/a
> Report document parsing errors at an early stage

- website/content/docs/integration.mdx
- website/pages/index.tsx
> docs: add vscode integration

- renovate.json
> chore: remove renovate limits

- website/app/playground/Playground.tsx
- website/app/playground/PlaygroundFooter.tsx
- website/app/playground/PlaygroundHeader.tsx
- website/app/playground/PlaygroundPreview.tsx
- website/app/playground/PlaygroundTab.tsx
> Update playground mobile viewport

- .github/workflows/docs.yml
> Fix last edited date

- packages/scaffdog/package.json
- pnpm-lock.yaml
Remove packages that are no longer needed.
n/a
n/a
- #829
> Remove `@types/wrap-ansi`

- package.json
- packages/@scaffdog/core/package.json
- packages/@scaffdog/core/src/extract.ts
- pnpm-lock.yaml
- website/package.json
Update packages related to Markdown processing.
n/a
n/a
- #838
- #831
- #825
- #822
- #812
> Update unified family

- packages/scaffdog/package.json
- packages/scaffdog/src/lib/prompt.ts
- packages/scaffdog/src/types/inquirer-autocomplete-prompt.d.ts
- pnpm-lock.yaml
Update inquirer packages.
n/a
n/a
- #818
- #817
> Update inquirer packages

- website/components/Header.tsx
- website/components/TableOfContent.tsx
- website/content/docs/index.mdx
> docs: tweak

- .changeset/proud-vans-melt.md
- packages/scaffdog/package.json
- packages/scaffdog/src/cli.ts
- pnpm-lock.yaml
> refactor: update `yargs` package

- .changeset/pre.json
- MIGRATION.md
- packages/scaffdog/README.md
> chore: exit canary

- .changeset/tasty-panthers-join.md
- .github/actions/setup-node/action.yml
- .github/workflows/ci.yml
- .github/workflows/docs.yml
- packages/scaffdog/README.md
Bye Node.js v16 :wave:
N/A
N/A
- N/A
> Require node v18

- .changeset/slimy-glasses-give.md
> chore: add changelog

- .github/workflows/docs.yml
> chore: update actions/deploy-pages

- renovate.json
> chore: tweak renovate config

- packages/prettier-plugin-scaffdog/src/index.ts
- packages/scaffdog/src/lib/question.ts
> chore: format

- .gitignore
> Add `.turbo` to gitignore

- .changeset/little-tables-cheer.md
- packages/scaffdog/src/index.ts
> Add export `Config` type
